use qrcode::{EcLevel, QrCode};

use crate::PromptPayError;

/// Trait defining output formatting capabilities for PromptPay payloads.
///
/// Implementations can convert the raw EMVCo payload into different formats:
/// - Plain string (for debugging or embedding)
/// - QR code image (`QrCode` from `qrcode` crate)
pub trait FormatterTrait {
    /// Returns the payload as a `String`.
    ///
    /// # Returns
    /// The complete EMVCo-compliant payload string.
    fn to_string(&self) -> String;

    /// Generates a QR code image from the payload.
    ///
    /// # Arguments
    /// * `ec_level` - Error correction level (higher = more robust but larger QR)
    ///
    /// # Returns
    /// * `Ok(QrCode)` - Successfully generated QR code
    /// * `Err(PromptPayError)` - If payload is empty or QR generation fails
    ///
    /// # Example
    /// ```rust
    /// use promptpay_rs::{Formatter, FormatterTrait, qrcode::{render::unicode, EcLevel}};
    /// let formatter = Formatter::new("000201010212...");
    /// let qr_code = formatter.to_image(EcLevel::M).unwrap();
    /// qr_code.render::<unicode::Dense1x2>().dark_color(unicode::Dense1x2::Light).light_color(unicode::Dense1x2::Dark).build();
    /// ```
    fn to_image(&self, ec_level: EcLevel) -> Result<QrCode, PromptPayError>;
}

/// A formatter that holds the raw PromptPay payload and provides conversion methods.
///
/// Created via [`Formatter::new()`] after generating the payload from [`PromptPayQR::create()`].
#[derive(Debug)]
pub struct Formatter {
    payload: String, // EMVCo-compliant payload string (includes CRC)
}

impl Formatter {
    /// Creates a new `Formatter` instance from a raw payload string.
    ///
    /// # Arguments
    /// * `payload` - The complete payload generated by `PromptPayQR::create()`
    ///
    /// # Returns
    /// A new `Formatter` instance ready for output conversion.
    ///
    /// # Example
    /// ```rust
    /// use promptpay_rs::Formatter;
    /// let formatter = Formatter::new("000201010212...");
    /// ```
    pub fn new(payload: &str) -> Self {
        Self {
            payload: payload.to_string(),
        }
    }
}

impl FormatterTrait for Formatter {
    fn to_string(&self) -> String {
        self.payload.clone() // คืนค่า payload ทั้งหมดแบบ clone เพื่อความปลอดภัย
    }

    fn to_image(&self, ec_level: EcLevel) -> Result<QrCode, PromptPayError> {
        // ตรวจสอบก่อนว่ามีข้อมูลหรือไม่
        if self.payload.is_empty() {
            return Err(PromptPayError::new("Payload cannot be empty"));
        }

        // ใช้ qrcode crate สร้าง QR code จาก bytes ของ payload
        // แปลงเป็น bytes เพื่อให้แน่ใจว่า encoding ถูกต้อง
        QrCode::with_error_correction_level(self.payload.as_bytes(), ec_level)
            .map_err(|e| PromptPayError::new(&format!("Failed to create QRCode: {}", e)))
    }
}
